# Generated by Django 2.0.1 on 2020-05-18 21:53

import cloudinary.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.TextField()),
                ('text_gr', models.TextField()),
                ('text_ru', models.TextField()),
                ('text_tr', models.TextField()),
                ('page_type', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=100)),
                ('status', models.CharField(default='1', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Admins',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('read_status', models.CharField(default='1', max_length=1)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Appointments',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_en', models.CharField(max_length=100)),
                ('address_gr', models.CharField(max_length=100)),
                ('address_ru', models.CharField(max_length=100)),
                ('address_tr', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_gr', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100)),
                ('name_tr', models.CharField(max_length=100)),
                ('description_en', models.TextField()),
                ('description_gr', models.TextField()),
                ('description_ru', models.TextField()),
                ('description_tr', models.TextField()),
                ('status', models.CharField(default='1', max_length=1)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('banner_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='banner_image')),
                ('full_name_en', models.CharField(max_length=100)),
                ('full_name_gr', models.CharField(max_length=100)),
                ('full_name_ru', models.CharField(max_length=100)),
                ('full_name_tr', models.CharField(max_length=100)),
                ('profession_en', models.CharField(max_length=100)),
                ('profession_gr', models.CharField(max_length=100)),
                ('profession_ru', models.CharField(max_length=100)),
                ('profession_tr', models.CharField(max_length=100)),
                ('description_en', models.TextField()),
                ('description_gr', models.TextField()),
                ('description_ru', models.TextField()),
                ('description_tr', models.TextField()),
                ('status', models.CharField(default='1', max_length=1)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Doctors',
            },
        ),
        migrations.CreateModel(
            name='DoctorQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='americanhospital_app.Doctor')),
            ],
            options={
                'verbose_name_plural': 'DoctorQuestion',
            },
        ),
        migrations.CreateModel(
            name='JobDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=100)),
                ('title_gr', models.CharField(max_length=100)),
                ('title_ru', models.CharField(max_length=100)),
                ('title_tr', models.CharField(max_length=100)),
                ('status', models.CharField(default='1', max_length=1)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Job Departments',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=100)),
                ('title_gr', models.CharField(max_length=100)),
                ('title_ru', models.CharField(max_length=100)),
                ('title_tr', models.CharField(max_length=100)),
                ('short_description_en', models.TextField()),
                ('short_description_gr', models.TextField()),
                ('short_description_ru', models.TextField()),
                ('short_description_tr', models.TextField()),
                ('description_en', models.TextField()),
                ('description_gr', models.TextField()),
                ('description_ru', models.TextField()),
                ('description_tr', models.TextField()),
                ('status', models.CharField(default='1', max_length=1)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('job_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='americanhospital_app.JobDepartment')),
            ],
            options={
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=100)),
                ('title_gr', models.CharField(max_length=100)),
                ('title_ru', models.CharField(max_length=100)),
                ('title_tr', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=30)),
                ('menu_type', models.CharField(max_length=20)),
                ('has_submenu', models.CharField(default='1', max_length=1)),
                ('status', models.CharField(default='1', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('read_status', models.CharField(default='1', max_length=1)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('title_en', models.CharField(max_length=100)),
                ('title_gr', models.CharField(max_length=100)),
                ('title_ru', models.CharField(max_length=100)),
                ('title_tr', models.CharField(max_length=100)),
                ('description_en', models.TextField()),
                ('description_gr', models.TextField()),
                ('description_ru', models.TextField()),
                ('description_tr', models.TextField()),
                ('keywords', models.TextField()),
                ('post_type', models.CharField(max_length=20)),
                ('display_home', models.CharField(default='1', max_length=1)),
                ('status', models.CharField(default='1', max_length=1)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='PatientGuide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=100)),
                ('title_gr', models.CharField(max_length=100)),
                ('title_ru', models.CharField(max_length=100)),
                ('title_tr', models.CharField(max_length=100)),
                ('text_en', models.TextField()),
                ('text_gr', models.TextField()),
                ('text_ru', models.TextField()),
                ('text_tr', models.TextField()),
                ('status', models.CharField(default='1', max_length=1)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'PatientGuide',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('read_status', models.CharField(default='1', max_length=1)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Results',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', cloudinary.models.CloudinaryField(max_length=255, verbose_name='file')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('bachelor', models.CharField(blank=True, max_length=100)),
                ('residency_program', models.CharField(blank=True, max_length=100)),
                ('read_status', models.CharField(default='1', max_length=1)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='americanhospital_app.Jobs')),
            ],
            options={
                'verbose_name_plural': 'Resume',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('title_en', models.CharField(max_length=100)),
                ('title_gr', models.CharField(max_length=100)),
                ('title_ru', models.CharField(max_length=100)),
                ('title_tr', models.CharField(max_length=100)),
                ('text_en', models.CharField(max_length=100)),
                ('text_gr', models.CharField(max_length=100)),
                ('text_ru', models.CharField(max_length=100)),
                ('text_tr', models.CharField(max_length=100)),
                ('status', models.CharField(default='1', max_length=1)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='americanhospital_app.Menu')),
            ],
            options={
                'verbose_name_plural': 'Sliders',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('status', models.CharField(default='1', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'SocialMedia',
            },
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=100)),
                ('title_gr', models.CharField(max_length=100)),
                ('title_ru', models.CharField(max_length=100)),
                ('title_tr', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=20)),
                ('status', models.CharField(default='1', max_length=1)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='americanhospital_app.Menu')),
            ],
            options={
                'verbose_name_plural': 'SubMenu',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('banner_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='banner_image')),
                ('full_name_en', models.CharField(max_length=100)),
                ('full_name_gr', models.CharField(max_length=100)),
                ('full_name_ru', models.CharField(max_length=100)),
                ('full_name_tr', models.CharField(max_length=100)),
                ('profession_en', models.CharField(max_length=100)),
                ('profession_gr', models.CharField(max_length=100)),
                ('profession_ru', models.CharField(max_length=100)),
                ('profession_tr', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('description_en', models.TextField()),
                ('description_gr', models.TextField()),
                ('description_ru', models.TextField()),
                ('description_tr', models.TextField()),
                ('status', models.CharField(default='1', max_length=1)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Team',
            },
        ),
        migrations.CreateModel(
            name='Thank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('to_whom', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('read_status', models.CharField(default='1', max_length=1)),
                ('text_type', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Thanks',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='americanhospital_app.Doctor'),
        ),
    ]
