# Generated by Django 2.0.1 on 2020-05-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('americanhospital_app', '0002_auto_20200519_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='speciality',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
