# Generated by Django 2.0.1 on 2020-06-21 14:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('americanhospital_app', '0003_resume_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorquestion',
            name='file',
            field=cloudinary.models.CloudinaryField(default='exit', max_length=255, verbose_name='file'),
            preserve_default=False,
        ),
    ]
