# Generated by Django 2.0.1 on 2020-07-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('americanhospital_app', '0004_doctorquestion_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
