# Generated by Django 2.0.1 on 2020-09-10 13:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('americanhospital_app', '0005_slider_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title_gr',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title_tr',
        ),
        migrations.AlterField(
            model_name='slider',
            name='text_en',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='slider',
            name='text_gr',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='slider',
            name='text_ru',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='slider',
            name='text_tr',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
