# Generated by Django 2.0.1 on 2020-09-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('americanhospital_app', '0006_auto_20200910_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='title_en',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='title_gr',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='title_ru',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='title_tr',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slider',
            name='text_en',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='slider',
            name='text_gr',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='slider',
            name='text_ru',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='slider',
            name='text_tr',
            field=models.CharField(max_length=100),
        ),
    ]
