# Generated by Django 2.0.1 on 2020-09-10 13:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('americanhospital_app', '0007_auto_20200910_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='test',
            field=ckeditor.fields.RichTextField(default=True),
            preserve_default=False,
        ),
    ]
