# Generated by Django 2.0.1 on 2020-09-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('americanhospital_app', '0015_keywords_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywords',
            name='status',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
