# Generated by Django 2.0.1 on 2020-09-18 12:13

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('americanhospital_app', '0018_tomail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepages',
            name='image',
        ),
        migrations.AddField(
            model_name='imagepages',
            name='department',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='imagepages',
            name='e_result',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='imagepages',
            name='text_department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imagepages',
            name='text_e_result',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
