# Generated by Django 2.0.1 on 2020-09-18 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('americanhospital_app', '0020_pageimage_pagetext'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageimage',
            name='page',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='americanhospital_app.PageText'),
            preserve_default=False,
        ),
    ]
