# Generated by Django 2.0.1 on 2020-09-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('americanhospital_app', '0021_pageimage_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetext',
            name='desc_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pagetext',
            name='desc_gr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pagetext',
            name='desc_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pagetext',
            name='desc_tr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
