# Generated by Django 2.0.1 on 2020-09-18 13:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('americanhospital_app', '0022_auto_20200918_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetext',
            name='desc_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagetext',
            name='desc_gr',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagetext',
            name='desc_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagetext',
            name='desc_tr',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagetext',
            name='title_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagetext',
            name='title_gr',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagetext',
            name='title_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagetext',
            name='title_tr',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
