# Generated by Django 2.0.1 on 2020-09-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('americanhospital_app', '0024_auto_20200918_1702'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagePages',
        ),
    ]
