# Generated by Django 2.0.1 on 2020-09-18 13:25

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('americanhospital_app', '0025_delete_imagepages'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalTechnologies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('title_en', models.CharField(max_length=100)),
                ('title_gr', models.CharField(max_length=100)),
                ('title_ru', models.CharField(max_length=100)),
                ('title_tr', models.CharField(max_length=100)),
                ('description_en', models.TextField()),
                ('description_gr', models.TextField()),
                ('description_ru', models.TextField()),
                ('description_tr', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
