# Generated by Django 2.0.1 on 2020-09-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('americanhospital_app', '0027_medicaltechnologies_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetext',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
