# Generated by Django 2.0.1 on 2020-09-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('americanhospital_app', '0028_pagetext_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='work_experience',
            field=models.DateField(blank=True, null=True),
        ),
    ]
