# Generated by Django 2.0.1 on 2020-09-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('americanhospital_app', '0029_doctor_work_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='work_experience',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
