# Generated by Django 2.0.1 on 2020-09-20 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('americanhospital_app', '0030_auto_20200920_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='americanhospital_app.Doctor'),
        ),
    ]
