# Generated by Django 2.0.1 on 2020-09-20 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('americanhospital_app', '0031_department_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='doctor',
        ),
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_department', to='americanhospital_app.Department'),
        ),
    ]
